http:
  port: "8081"
  
american:
  host: "training4-american-ws1-mod5.us-e2.cloudhub.io"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  client_id: "dbfa09a8364542d19c5ddd0b3814367e"
  client_secret: "e37a3E24ba9E4650AB58C37774AF1258"
  
training:
  host: "mu.learn.mulesoft.com"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  
delta:
  wsdl: "http://mu.learn.mulesoft.com/delta?wsdl"
  service: "TicketServiceService"
  port: "TicketServicePort"